name: Docker Build Check

on:
  pull_request:
    paths:
      - 'apps/api/**'
      - 'packages/shared/**'
      - '.github/workflows/docker-build.yml'

jobs:
  docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: false
          tags: etsy-manager-api:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run -d --name test-api -p 3001:3001 etsy-manager-api:test
          sleep 10
          curl -f http://localhost:3001/health || exit 1
          docker logs test-api
          docker stop test-api
